name: testing

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Test
            uses: actions/checkout@v3
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test --if-present

        - name: Create changelog
            id: changelog
            uses: dragonraid/changelog-emitter
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
